name: 🤖 Advancia Auto Manager

on:
  push:
    branches: ["main"]
  issues:
    types: [opened, reopened, edited]
  workflow_dispatch:

permissions:
  issues: write
  contents: read
  actions: write
  deployments: write
  pages: write
  id-token: write

jobs:
  setup-labels:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub CLI
        run: |
          type gh >/dev/null 2>&1 || { echo "gh CLI already available"; }

      - name: Create Advancia Label Set
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh label create "RPA" --color "00B8D9" --description "RPA automation and robotic process tasks" --force --repo ${{ github.repository }} || true
          gh label create "CI/CD" --color "4C9AFF" --description "Build pipelines and deployments" --force --repo ${{ github.repository }} || true
          gh label create "backend" --color "FFAB00" --description "Backend-related (Node.js, Prisma, API, migrations)" --force --repo ${{ github.repository }} || true
          gh label create "frontend" --color "36B37E" --description "Frontend/UI (Next.js, MedBed, Dashboard)" --force --repo ${{ github.repository }} || true
          gh label create "render" --color "6554C0" --description "Render hosting, deployment or environment issues" --force --repo ${{ github.repository }} || true
          gh label create "cloudflare" --color "2684FF" --description "Cloudflare configuration, DNS or SSL issues" --force --repo ${{ github.repository }} || true
          gh label create "automation" --color "B3D4FF" --description "Automated tasks and process optimization" --force --repo ${{ github.repository }} || true
          gh label create "urgent" --color "DE350B" --description "Critical production blockers" --force --repo ${{ github.repository }} || true
          gh label create "AI-analysis" --color "FFC400" --description "GPT-5 or AI auto-triage analyzed issues" --force --repo ${{ github.repository }} || true
          gh label create "enhancement" --color "0052CC" --description "Feature improvement or code upgrade" --force --repo ${{ github.repository }} || true
          gh label create "bug" --color "FF5630" --description "General bug or issue" --force --repo ${{ github.repository }} || true
          gh label create "database" --color "8777D9" --description "Prisma, DB or query issues" --force --repo ${{ github.repository }} || true
          gh label create "render-health" --color "00875A" --description "Render health check failures or alerts" --force --repo ${{ github.repository }} || true
          gh label create "resolved" --color "006644" --description "Resolved automatically or manually" --force --repo ${{ github.repository }} || true
          echo "✅ All labels created successfully"

  triage:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Analyze issue context
        id: detect
        run: |
          TITLE="${{ github.event.issue.title }}"
          BODY="${{ github.event.issue.body }}"

          LABELS=""
          if echo "$TITLE $BODY" | grep -iqE 'rpa|automation|bot'; then
            LABELS="RPA,automation"
          elif echo "$TITLE $BODY" | grep -iqE 'deploy|render|build|pipeline'; then
            LABELS="CI/CD,render"
          elif echo "$TITLE $BODY" | grep -iqE 'dns|cloudflare|ssl'; then
            LABELS="cloudflare"
          elif echo "$TITLE $BODY" | grep -iqE 'backend|api|prisma|migration'; then
            LABELS="backend,database"
          elif echo "$TITLE $BODY" | grep -iqE 'frontend|next|dashboard|ui'; then
            LABELS="frontend"
          elif echo "$TITLE $BODY" | grep -iqE 'urgent|critical|down'; then
            LABELS="urgent"
          elif echo "$TITLE $BODY" | grep -iqE 'bug|error|fail'; then
            LABELS="bug"
          else
            LABELS="AI-analysis"
          fi

          echo "labels=$LABELS" >> $GITHUB_OUTPUT
          echo "Detected labels: $LABELS"

      - name: Apply detected labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.detect.outputs.labels }}

      - name: Confirm labels
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            🤖 **Advancia RPA Auto Manager**

            ✅ Auto-labels applied: `${{ steps.detect.outputs.labels }}`

            This issue has been automatically categorized. Labels can be adjusted manually if needed.

            ---
            *Powered by Advancia Platform Automation*
