name: 🤖 Advancia Full RPA Validation + Auto-Deploy

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: read

env:
  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
  RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}

jobs:
  # 1️⃣ RPA VALIDATION
  rpa-validation:
    name: 🔍 Validate Build via RPA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: RPA Validation (Lint + Build)
        run: |
          echo "🚀 Running automated RPA validation..."
          npm run lint || echo "⚠ Lint warnings present"
          npm run build || (echo "❌ Build failed" && exit 1)
          echo "✅ Build passed validation checks."

      - name: Optional Health Check
        run: |
          echo "🌐 Checking backend health..."
          curl -f http://localhost:4000/health || echo "⚠ Backend not reachable (may require live env)"
          echo "✅ Validation done."

  # 2️⃣ AUTO-APPROVE SAFE PULL REQUESTS
  auto-approve:
    needs: rpa-validation
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && (
        github.actor == 'github-actions[bot]' ||
        contains(github.event.pull_request.title, 'deploy') ||
        contains(github.event.pull_request.title, 'docs') ||
        contains(github.event.pull_request.title, 'feat')
      )
    steps:
      - name: ✅ Auto-approve safe PRs
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  # 3️⃣ AUTO-MERGE AFTER RPA VALIDATION
  auto-merge:
    needs: [rpa-validation, auto-approve]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: ⚙ Auto-merge PRs
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: squash
          MERGE_LABELS: "automerge,approved"
          MERGE_RETRIES: 6
          MERGE_RETRY_SLEEP: 10000

  # 4️⃣ DEPLOY TO RENDER AFTER MERGE
  render-deploy:
    needs: rpa-validation
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: 🚀 Trigger Render Deployment
        run: |
          echo "🚀 Triggering Render deploy for $RENDER_SERVICE_ID ..."
          if [ -z "$RENDER_SERVICE_ID" ] || [ -z "$RENDER_TOKEN" ]; then
            echo "⚠️ RENDER_SERVICE_ID or RENDER_TOKEN not set, skipping deploy"
            exit 0
          fi
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_TOKEN" \
            -H "Content-Type: application/json"
          echo "✅ Render deployment triggered."

      - name: Wait for deployment
        run: |
          echo "⏳ Waiting 90 seconds for deployment to complete..."
          sleep 90

      - name: Verify deployment health
        run: |
          echo "🔍 Checking deployed site health..."
          for i in {1..10}; do
            if curl -f https://advanciapayledger.com/api/health; then
              echo "✅ Deployment healthy!"
              exit 0
            fi
            echo "Attempt $i/10 failed, retrying..."
            sleep 6
          done
          echo "⚠️ Health check failed after 10 attempts"
          exit 1
