name: Deploy to Render (Compat Secrets)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Select hooks from secrets
        id: hooks
        env:
          RENDER_DEPLOY_HOOK_BACKEND: ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
          RENDER_DEPLOY_HOOK_FRONTEND: ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
          RENDER_BACKEND_HOOK: ${{ secrets.RENDER_BACKEND_HOOK }}
          RENDER_FRONTEND_HOOK: ${{ secrets.RENDER_FRONTEND_HOOK }}
        run: |
          BACKEND_HOOK="${RENDER_DEPLOY_HOOK_BACKEND:-${RENDER_BACKEND_HOOK:-}}"
          FRONTEND_HOOK="${RENDER_DEPLOY_HOOK_FRONTEND:-${RENDER_FRONTEND_HOOK:-}}"
          if [ -n "$BACKEND_HOOK" ]; then echo "backend=true" >> $GITHUB_OUTPUT; else echo "backend=false" >> $GITHUB_OUTPUT; fi
          if [ -n "$FRONTEND_HOOK" ]; then echo "frontend=true" >> $GITHUB_OUTPUT; else echo "frontend=false" >> $GITHUB_OUTPUT; fi
          echo "BACKEND_HOOK=$BACKEND_HOOK" >> $GITHUB_ENV
          echo "FRONTEND_HOOK=$FRONTEND_HOOK" >> $GITHUB_ENV

      - name: Trigger backend Render deployment
        if: ${{ steps.hooks.outputs.backend == 'true' }}
        env:
          BACKEND_HOOK: ${{ env.BACKEND_HOOK }}
        run: |
          echo "Deploying backend to Render..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --request POST --url "$BACKEND_HOOK" --header 'content-type: application/json')
          echo "Backend hook HTTP $STATUS"

      - name: Trigger frontend Render deployment
        if: ${{ steps.hooks.outputs.frontend == 'true' }}
        env:
          FRONTEND_HOOK: ${{ env.FRONTEND_HOOK }}
        run: |
          echo "Deploying frontend to Render..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --request POST --url "$FRONTEND_HOOK" --header 'content-type: application/json')
          echo "Frontend hook HTTP $STATUS"

      - name: Skip (no hooks)
        if: ${{ steps.hooks.outputs.backend != 'true' && steps.hooks.outputs.frontend != 'true' }}
        run: echo "No Render hooks configured; skipping. Add secrets RENDER_BACKEND_HOOK and/or RENDER_FRONTEND_HOOK."
