name: Deploy on CI Success (Render)

on:
  workflow_run:
    workflows: ["CI - Test & Build", "CI"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    if: >
      ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Select hooks from secrets
        id: hooks
        env:
          RENDER_DEPLOY_HOOK_BACKEND: ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
          RENDER_DEPLOY_HOOK_FRONTEND: ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
          RENDER_BACKEND_HOOK: ${{ secrets.RENDER_BACKEND_HOOK }}
          RENDER_FRONTEND_HOOK: ${{ secrets.RENDER_FRONTEND_HOOK }}
        run: |
          BACKEND_HOOK="${RENDER_DEPLOY_HOOK_BACKEND:-${RENDER_BACKEND_HOOK:-}}"
          FRONTEND_HOOK="${RENDER_DEPLOY_HOOK_FRONTEND:-${RENDER_FRONTEND_HOOK:-}}"
          if [ -n "$BACKEND_HOOK" ]; then echo "backend=true" >> $GITHUB_OUTPUT; else echo "backend=false" >> $GITHUB_OUTPUT; fi
          if [ -n "$FRONTEND_HOOK" ]; then echo "frontend=true" >> $GITHUB_OUTPUT; else echo "frontend=false" >> $GITHUB_OUTPUT; fi
          echo "BACKEND_HOOK=$BACKEND_HOOK" >> $GITHUB_ENV
          echo "FRONTEND_HOOK=$FRONTEND_HOOK" >> $GITHUB_ENV

      - name: Trigger backend Render deployment
        if: ${{ steps.hooks.outputs.backend == 'true' }}
        env:
          BACKEND_HOOK: ${{ env.BACKEND_HOOK }}
        run: |
          echo "Deploying backend to Render..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --request POST --url "$BACKEND_HOOK")
          echo "Backend hook HTTP $STATUS"

      - name: Trigger frontend Render deployment
        if: ${{ steps.hooks.outputs.frontend == 'true' }}
        env:
          FRONTEND_HOOK: ${{ env.FRONTEND_HOOK }}
        run: |
          echo "Deploying frontend to Render..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --request POST --url "$FRONTEND_HOOK")
          echo "Frontend hook HTTP $STATUS"

      - name: Skip (no hooks configured)
        if: ${{ steps.hooks.outputs.backend != 'true' && steps.hooks.outputs.frontend != 'true' }}
        run: echo "No Render deploy hooks configured; set repo secrets to enable deployment."
