name: Deploy Now (Render)

on:
  workflow_dispatch:
    inputs:
      deployBackend:
        type: boolean
        description: "Trigger backend deploy"
        default: true
      deployFrontend:
        type: boolean
        description: "Trigger frontend deploy"
        default: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Select hooks from secrets
        id: hooks
        env:
          RENDER_DEPLOY_HOOK_BACKEND: ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
          RENDER_DEPLOY_HOOK_FRONTEND: ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
          RENDER_BACKEND_HOOK: ${{ secrets.RENDER_BACKEND_HOOK }}
          RENDER_FRONTEND_HOOK: ${{ secrets.RENDER_FRONTEND_HOOK }}
        run: |
          BACKEND_HOOK="${RENDER_DEPLOY_HOOK_BACKEND:-${RENDER_BACKEND_HOOK:-}}"
          FRONTEND_HOOK="${RENDER_DEPLOY_HOOK_FRONTEND:-${RENDER_FRONTEND_HOOK:-}}"
          echo "BACKEND_HOOK=$BACKEND_HOOK" >> $GITHUB_ENV
          echo "FRONTEND_HOOK=$FRONTEND_HOOK" >> $GITHUB_ENV

      - name: Trigger backend Render deployment
        if: ${{ inputs.deployBackend == true && env.BACKEND_HOOK != '' }}
        env:
          BACKEND_HOOK: ${{ env.BACKEND_HOOK }}
        run: |
          echo "Deploying backend to Render..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --request POST --url "$BACKEND_HOOK")
          echo "Backend hook HTTP $STATUS"

      - name: Trigger frontend Render deployment
        if: ${{ inputs.deployFrontend == true && env.FRONTEND_HOOK != '' }}
        env:
          FRONTEND_HOOK: ${{ env.FRONTEND_HOOK }}
        run: |
          echo "Deploying frontend to Render..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --request POST --url "$FRONTEND_HOOK")
          echo "Frontend hook HTTP $STATUS"

      - name: Skip (no hooks configured)
        if: ${{ (inputs.deployBackend == true && env.BACKEND_HOOK == '') && (inputs.deployFrontend == true && env.FRONTEND_HOOK == '') }}
        run: echo "No Render deploy hooks configured; set repo secrets to enable deployment."
