name: 🔁 Full Nightly Auto-Redeploy (Advancia)

on:
  schedule:
    # Runs daily at 3 AM UTC (10 PM EST / 7 PM PST)
    # Adjust schedule: https://crontab.guru
    - cron: "0 3 * * *"
  
  workflow_dispatch:  # Allow manual trigger from GitHub Actions tab
    inputs:
      deploy_backend:
        description: 'Deploy backend service'
        required: false
        default: 'true'
        type: boolean
      deploy_frontend:
        description: 'Deploy frontend service'
        required: false
        default: 'true'
        type: boolean

jobs:
  full-redeploy:
    name: Full Stack Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'- name: 🔧 Verify PowerShell
        shell: pwsh
        run: |
          Write-Host "✅ PowerShell $($PSVersionTable.PSVersion) ready" -ForegroundColor Green
          Write-Host "📍 Working directory: $(Get-Location)" -ForegroundColor Cyan

      - name: 🔐 Create .env from GitHub Secrets
        run: |
          echo "# Auto-generated by GitHub Actions - $(date -u)" > .env
          echo "RENDER_API_KEY=${{ secrets.RENDER_API_KEY }}" >> .env
          echo "RENDER_SERVICE_ID=${{ secrets.RENDER_FRONTEND_SERVICE_ID || secrets.RENDER_SERVICE_ID }}" >> .env
          echo "RENDER_FRONTEND_SERVICE_ID=${{ secrets.RENDER_FRONTEND_SERVICE_ID }}" >> .env
          echo "RENDER_BACKEND_SERVICE_ID=${{ secrets.RENDER_BACKEND_SERVICE_ID }}" >> .env
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> .env
          echo "CLOUDFLARE_ZONE_ID=${{ secrets.CLOUDFLARE_ZONE_ID }}" >> .env
          echo "CLOUDFLARE_DOMAIN=advanciapayledger.com" >> .env
          echo "CI=true" >> .env
          echo "✅ Environment configured with $( (Get-Content .env | Measure-Object -Line).Lines ) variables"
        shell: pwsh

      # === BACKEND DEPLOYMENT ===
      - name: 🧱 Backend Build & Deploy
        if: github.event.inputs.deploy_backend != 'false'
        shell: pwsh
        continue-on-error: true
        run: |
          Write-Host "`n🔨 Starting Backend Deployment..." -ForegroundColor Cyan
          
          if (Test-Path ./scripts/render-backend-auto.ps1) {
            pwsh ./scripts/render-backend-auto.ps1 2>&1 | Tee-Object -FilePath deploy-backend.log
            Write-Host "✅ Backend deployment script completed" -ForegroundColor Green
          } else {
            Write-Host "⚠ Backend deployment script not found, triggering via API..." -ForegroundColor Yellow
            
            $backendServiceId = $env:RENDER_BACKEND_SERVICE_ID
            $renderApiKey = $env:RENDER_API_KEY
            
            if ($backendServiceId -and $renderApiKey) {
              $headers = @{
                "Authorization" = "Bearer $renderApiKey"
                "Content-Type" = "application/json"
              }
              $url = "https://api.render.com/v1/services/$backendServiceId/deploys"
              
              try {
                $response = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body "{}"
                Write-Host "✅ Backend deployment triggered via API" -ForegroundColor Green
                "Backend deployment: Success - Deploy ID: $($response.id)" | Out-File -Append deploy-backend.log
              } catch {
                Write-Host "❌ Backend API deployment failed: $($_.Exception.Message)" -ForegroundColor Red
                "Backend deployment: Failed - $($_.Exception.Message)" | Out-File -Append deploy-backend.log
              }
            } else {
              Write-Host "⏭ Backend deployment skipped (credentials not configured)" -ForegroundColor Gray
              "Backend deployment: Skipped - No credentials" | Out-File deploy-backend.log
            }
          }

      # === FRONTEND DEPLOYMENT ===
      - name: 🌐 Frontend Build & Deploy + DNS Auto-Heal
        if: github.event.inputs.deploy_frontend != 'false'
        shell: pwsh
        run: |
          Write-Host "`n🔨 Starting Frontend Deployment..." -ForegroundColor Cyan
          pwsh ./scripts/render-frontend-auto.ps1 2>&1 | Tee-Object -FilePath deploy-frontend.log
          Write-Host "✅ Frontend deployment completed" -ForegroundColor Green

      # === VERIFICATION ===
      - name: 🔍 Verify Live Endpoints
        run: |
          echo "🌐 Verifying deployment endpoints..." > deploy-checks.log
          echo "" >> deploy-checks.log
          
          # Wait for deployment propagation
          sleep 45
          
          # Check frontend
          echo "Checking frontend: https://advanciapayledger.com" >> deploy-checks.log
          FRONTEND_STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://advanciapayledger.com || echo "000")
          echo "  Status: HTTP $FRONTEND_STATUS" >> deploy-checks.log
          
          if [ "$FRONTEND_STATUS" == "200" ] || [ "$FRONTEND_STATUS" == "301" ] || [ "$FRONTEND_STATUS" == "302" ]; then
            echo "  ✅ Frontend is live!" >> deploy-checks.log
          else
            echo "  ⚠️ Frontend returned unexpected status" >> deploy-checks.log
          fi
          
          # Check backend
          echo "" >> deploy-checks.log
          echo "Checking backend: https://api.advanciapayledger.com/health" >> deploy-checks.log
          BACKEND_STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://api.advanciapayledger.com/health || echo "000")
          echo "  Status: HTTP $BACKEND_STATUS" >> deploy-checks.log
          
          if [ "$BACKEND_STATUS" == "200" ]; then
            echo "  ✅ Backend health check passed!" >> deploy-checks.log
          else
            echo "  ⚠️ Backend health check failed or not configured" >> deploy-checks.log
          fi
          
          # Display results
          cat deploy-checks.log

      # === ARTIFACTS ===
      - name: 📦 Upload Deployment Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: advancia-deploy-logs-${{ github.run_number }}
          path: |
            deploy-backend.log
            deploy-frontend.log
            deploy-checks.log
          retention-days: 30

      # === NOTIFICATIONS ===
      - name: 📣 Slack Notification
        if: always() && secrets.SLACK_WEBHOOK != ''
        run: |
          STATUS="${{ job.status }}"
          ICON="✅"
          COLOR="#36a64f"
          
          if [ "$STATUS" != "success" ]; then
            ICON="⚠️"
            COLOR="#ff9900"
          fi
          
          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"attachments\": [{
                \"color\": \"$COLOR\",
                \"title\": \"$ICON Advancia Nightly Deployment\",
                \"text\": \"Status: $STATUS\",
                \"fields\": [
                  {\"title\": \"Trigger\", \"value\": \"${{ github.event_name }}\", \"short\": true},
                  {\"title\": \"Timestamp\", \"value\": \"$(date -u)\", \"short\": true}
                ],
                \"actions\": [
                  {\"type\": \"button\", \"text\": \"View Logs\", \"url\": \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}
                ]
              }]
            }" \
            ${{ secrets.SLACK_WEBHOOK }} || echo "Slack notification failed"

      - name: 📧 Email Notification
        if: always() && secrets.EMAIL_USERNAME != '' && secrets.EMAIL_PASSWORD != ''
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "${{ job.status == 'success' && '✅' || '⚠️' }} Advancia Nightly Deploy - ${{ job.status }}"
          to: ${{ secrets.EMAIL_RECIPIENT || secrets.EMAIL_USERNAME }}
          from: "Advancia Deploy Bot <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            Deployment Report for advanciapayledger.com
            
            Status: ${{ job.status }}
            Trigger: ${{ github.event_name }}
            Timestamp: ${{ github.event.head_commit.timestamp }}
            Run ID: ${{ github.run_id }}
            
            Endpoints Checked:
            - Frontend: https://advanciapayledger.com
            - Backend: https://api.advanciapayledger.com/health
            
            View full logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          attachments: |
            deploy-backend.log
            deploy-frontend.log
            deploy-checks.log
          convert_markdown: true

      # === SUMMARY ===
      - name: 📊 Deployment Summary
        if: always()
        run: |
          echo "## 🚀 Full Stack Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📋 Deployment Status" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Component | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Overall | ${{ job.status }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Backend | $([ -f deploy-backend.log ] && echo '✅ Deployed' || echo '⏭️ Skipped') |" >> $GITHUB_STEP_SUMMARY
          echo "| Frontend | $([ -f deploy-frontend.log ] && echo '✅ Deployed' || echo '⏭️ Skipped') |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🌐 Live Endpoints" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Frontend**: [advanciapayledger.com](https://advanciapayledger.com)" >> $GITHUB_STEP_SUMMARY
          echo "- **Backend**: [api.advanciapayledger.com](https://api.advanciapayledger.com/health)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔗 Management Links" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- [Render Dashboard](https://dashboard.render.com)" >> $GITHUB_STEP_SUMMARY
          echo "- [Cloudflare Dashboard](https://dash.cloudflare.com)" >> $GITHUB_STEP_SUMMARY
          echo "- [View Deployment Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_STEP_SUMMARY

