name: Post-Deploy Smoke (Backend Health)

on:
  workflow_run:
    workflows:
      [
        "Deploy on CI Success (Render)",
        "Deploy to Render (Compat Secrets)",
        "Deploy to Render",
      ]
    types: [completed]
  workflow_dispatch:
    inputs:
      baseUrl:
        description: "Backend base URL (e.g., https://<service>.onrender.com)"
        required: false
        default: ""

jobs:
  smoke:
    if: >
      ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Resolve base URL
        id: cfg
        env:
          INPUT_BASE: ${{ github.event.inputs.baseUrl }}
          SECRET_BASE: ${{ secrets.RENDER_BACKEND_BASE_URL }}
        run: |
          BASE="$INPUT_BASE"
          if [ -z "$BASE" ] && [ -n "$SECRET_BASE" ]; then BASE="$SECRET_BASE"; fi
          if [ -z "$BASE" ]; then echo "No base URL provided; skipping smoke"; echo "skip=true" >> $GITHUB_OUTPUT; else echo "BASE=$BASE" >> $GITHUB_ENV; fi

      - name: Skip if no base
        if: ${{ steps.cfg.outputs.skip == 'true' }}
        run: echo "No base URL set via input or secret RENDER_BACKEND_BASE_URL."

      - name: Health check /api/health
        if: ${{ steps.cfg.outputs.skip != 'true' }}
        env:
          BASE: ${{ env.BASE }}
        run: |
          echo "Probing $BASE/api/health"
          code=$(curl -s -o /tmp/hbody -w "%{http_code}" "$BASE/api/health" || true)
          echo "Status: $code"
          echo "Body:"; cat /tmp/hbody || true
          if [ "$code" != "200" ]; then echo "Health check failed" >&2; exit 1; fi
