name: Advancia RPA Auto Deploy & Self-Heal

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */4 * * *" # Health check every 4 hours
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    name: Build, Deploy & Health Check
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"- name: 📦 Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: 📦 Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: 🧩 Generate Prisma Client
        working-directory: ./backend
        run: npx prisma generate

      - name: 🔍 TypeScript Check - Backend
        working-directory: ./backend
        run: npx tsc --noEmit
        continue-on-error: true

      - name: 🔍 TypeScript Check - Frontend
        working-directory: ./frontend
        run: npx tsc --noEmit
        continue-on-error: true

      - name: 🧱 Build Backend
        working-directory: ./backend
        run: npm run build

      - name: 🧱 Build Frontend
        working-directory: ./frontend
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
        run: |
          export NEXT_PUBLIC_API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL:-https://api.advanciapayledger.com}"
          npm run build

      - name: 🚀 Trigger Render Deployment
        if: success()
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "🚀 Triggering Render deployment..."
          DEPLOY_RESPONSE=$(curl -sS -X POST \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": false}')

          DEPLOY_ID=$(echo "$DEPLOY_RESPONSE" | jq -r '.id')
          if [ -z "$DEPLOY_ID" ] || [ "$DEPLOY_ID" = "null" ]; then
            echo "❌ Failed to trigger deployment"
            echo "$DEPLOY_RESPONSE" | jq '.' || echo "$DEPLOY_RESPONSE"
            exit 1
          fi
          echo "✅ Deploy triggered - ID: $DEPLOY_ID"
          echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_ENV

      - name: ⏳ Monitor Deployment
        if: success()
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "⏳ Monitoring deployment..."
          for i in {1..30}; do
            sleep 10
            STATUS=$(curl -s "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys/${{ env.DEPLOY_ID }}" \
              -H "Authorization: Bearer $RENDER_API_KEY" | jq -r '.status')
            
            echo "[$i/30] Status: $STATUS"
            
            if [ "$STATUS" = "live" ]; then
              echo "🎉 Deployment succeeded!"
              exit 0
            elif [ "$STATUS" = "failed" ]; then
              echo "❌ Deployment failed"
              exit 1
            fi
          done

          echo "⏱️ Monitoring timeout"
          exit 1

      - name: 🏥 Production Health Check
        if: success()
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          echo "🏥 Checking production health..."
          RESOLVED_BACKEND_URL="${BACKEND_URL:-https://api.advanciapayledger.com}"
          sleep 30
          for i in {1..10}; do
            if curl -f -s "$RESOLVED_BACKEND_URL/api/health" > /dev/null; then
              echo "✅ Backend is healthy!"
              exit 0
            fi
            echo "⏳ Waiting for backend... attempt $i/10"
            sleep 30
          done
          echo "❌ Backend health check failed"
          exit 1

      - name: 🌐 Purge Cloudflare Cache
        if: success()
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          if [ -z "$CLOUDFLARE_ZONE_ID" ] || [ -z "$CLOUDFLARE_API_TOKEN" ]; then
            echo "⚠️ Cloudflare credentials not set - skipping cache purge"
            exit 0
          fi
          echo "🌐 Purging Cloudflare cache..."
          PURGE_RESPONSE=$(curl -X POST \
            "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"purge_everything": true}')
          SUCCESS=$(echo $PURGE_RESPONSE | jq -r '.success')
          if [ "$SUCCESS" = "true" ]; then
            PURGE_ID=$(echo $PURGE_RESPONSE | jq -r '.result.id // "N/A"')
            echo "✅ Cloudflare cache purged successfully"
            echo "   Purge ID: $PURGE_ID"
          else
            echo "⚠️ Cache purge failed:"
            echo $PURGE_RESPONSE | jq '.errors'
            exit 0
          fi

      - name: ✅ Success Notification
        if: success()
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          RESOLVED_BACKEND_URL="${BACKEND_URL:-https://api.advanciapayledger.com}"
          echo "🎉 ================================"
          echo "✅ DEPLOYMENT SUCCESSFUL!"
          echo "================================"
          echo "Backend: $RESOLVED_BACKEND_URL"
          echo "Frontend: https://advanciapayledger.com"
          echo "CDN: Cache purged (Cloudflare)"
          echo "Time: $(date)"
          echo "Commit: ${{ github.sha }}"

      - name: 🚨 Failure - Create Issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = `🚨 Deployment Failed - ${new Date().toISOString()}`;
            const body = `
            ## Deployment Failure Report

            **Workflow:** ${context.workflow}
            **Run ID:** ${context.runId}
            **Commit:** ${context.sha.substring(0, 7)}
            **Branch:** ${context.ref}
            **Actor:** @${context.actor}

            ### Logs
            [View workflow logs](${context.payload.repository.html_url}/actions/runs/${context.runId})

            ### What to check
            - [ ] TypeScript compilation errors
            - [ ] Prisma migration status
            - [ ] Build errors in backend/frontend
            - [ ] Render deployment logs
            - [ ] Production health endpoint status
            - [ ] Environment variables (secrets)

            ### Auto-created by GitHub Actions
            This issue was automatically created because deployment failed.
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['deployment', 'automated', 'urgent']
            });

      - name: 🧹 Log Maintenance (Scheduled Only)
        if: github.event_name == 'schedule'
        run: |
          echo "🧹 Running log maintenance..."
          # This runs only on scheduled checks, not on every push
          echo "Log cleanup would run here (implementation in PowerShell script)"

