# PowerShell Script to Set Up Test Environment
# Run this script to create .env.test.local and guide through database setup

Write-Host "Test Environment Setup Script" -ForegroundColor Cyan
Write-Host ""

# Check if .env.test.local already exists
$envFile = ".env.test.local"
if (Test-Path $envFile) {
    Write-Host "[!] .env.test.local already exists" -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Aborted." -ForegroundColor Red
        exit 1
    }
}

# Default values
$defaultDbUrl = "postgresql://test:test@localhost:5432/test"
$defaultEmail = "test@example.com"
$defaultPassword = "test_password_123"

Write-Host "Test Database Configuration" -ForegroundColor Blue
Write-Host ""

# Prompt for DATABASE_URL_TEST
Write-Host "Enter DATABASE_URL_TEST (or press Enter for default):"
Write-Host "Default: $defaultDbUrl" -ForegroundColor Gray
$dbUrl = Read-Host "DATABASE_URL_TEST"
if ([string]::IsNullOrWhiteSpace($dbUrl)) {
    $dbUrl = $defaultDbUrl
}

# Prompt for TEST_USER_EMAIL
Write-Host ""
Write-Host "Test User Email" -ForegroundColor Blue
Write-Host "Enter TEST_USER_EMAIL (or press Enter for default):"
Write-Host "Default: $defaultEmail" -ForegroundColor Gray
$testEmail = Read-Host "TEST_USER_EMAIL"
if ([string]::IsNullOrWhiteSpace($testEmail)) {
    $testEmail = $defaultEmail
}

# Prompt for TEST_USER_PASSWORD
Write-Host ""
Write-Host "Test User Password" -ForegroundColor Blue
Write-Host "Enter TEST_USER_PASSWORD (or press Enter for default):"
Write-Host "Default: $defaultPassword" -ForegroundColor Gray
$testPassword = Read-Host "TEST_USER_PASSWORD"
if ([string]::IsNullOrWhiteSpace($testPassword)) {
    $testPassword = $defaultPassword
}

# Create .env.test.local file
$content = @"
# Test Environment Variables
# Generated by setup-test-env.ps1
# DO NOT COMMIT TO GIT

# Test Database URL
DATABASE_URL_TEST=$dbUrl

# Test User Credentials (for E2E tests)
TEST_USER_EMAIL=$testEmail
TEST_USER_PASSWORD=$testPassword

# Test Environment
NODE_ENV=test
"@

try {
    $content | Out-File -FilePath $envFile -Encoding utf8 -NoNewline
    Write-Host ""
    Write-Host "[OK] Created .env.test.local" -ForegroundColor Green
    Write-Host ""
    Write-Host "Variables set:" -ForegroundColor Cyan
    Write-Host "  DATABASE_URL_TEST=$dbUrl"
    Write-Host "  TEST_USER_EMAIL=$testEmail"
    Write-Host "  TEST_USER_PASSWORD=$testPassword"
    Write-Host ""
} catch {
    Write-Host ""
    Write-Host "[ERROR] Failed to create .env.test.local: $_" -ForegroundColor Red
    exit 1
}

# Check for PostgreSQL
Write-Host ""
Write-Host "Checking for PostgreSQL..." -ForegroundColor Blue

$psqlFound = $false
try {
    $psqlVersion = & psql --version 2>&1
    if ($LASTEXITCODE -eq 0) {
        $psqlFound = $true
        Write-Host "[OK] PostgreSQL found: $psqlVersion" -ForegroundColor Green
    }
} catch {
    # psql not found
}

if (-not $psqlFound) {
    Write-Host "[!] PostgreSQL not found in PATH" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "💡 Next Steps:" -ForegroundColor Cyan
    Write-Host "   1. Install PostgreSQL: https://www.postgresql.org/download/windows/"
    Write-Host "   2. Or install Docker Desktop: https://www.docker.com/products/docker-desktop"
    Write-Host "   3. Then run: npm run test:db:setup (for Docker)"
    Write-Host ""
} else {
    Write-Host ""
    Write-Host "💡 Next Steps:" -ForegroundColor Cyan
    Write-Host "   1. Create test database:"
    Write-Host "      psql -U postgres -c `"CREATE DATABASE test;`""
    Write-Host "      psql -U postgres -c `"CREATE USER test WITH PASSWORD 'test';`""
    Write-Host "      psql -U postgres -c `"GRANT ALL PRIVILEGES ON DATABASE test TO test;`""
    Write-Host ""
    Write-Host "   2. Verify setup:"
    Write-Host "      npm run test:env"
    Write-Host "      npm run test:db"
    Write-Host ""
}

Write-Host "[OK] Setup script complete!" -ForegroundColor Green
Write-Host ""

