#!/bin/bash

# Setup Test Environment Variables
# This script helps set up test environment variables for local development

set -e

echo "🧪 Setting up test environment variables..."
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if .env.test.local exists
if [ -f ".env.test.local" ]; then
    echo -e "${YELLOW}⚠️  .env.test.local already exists${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
fi

# Default values
DEFAULT_DB_URL="postgresql://test:test@localhost:5432/test"
DEFAULT_TEST_EMAIL="test@example.com"
DEFAULT_TEST_PASSWORD="test_password_123"

# Prompt for DATABASE_URL_TEST
echo -e "${BLUE}📊 Test Database URL${NC}"
echo "Enter DATABASE_URL_TEST (or press Enter for default):"
echo "Default: $DEFAULT_DB_URL"
read -p "DATABASE_URL_TEST: " DB_URL
DB_URL=${DB_URL:-$DEFAULT_DB_URL}

# Prompt for TEST_USER_EMAIL
echo ""
echo -e "${BLUE}📧 Test User Email${NC}"
echo "Enter TEST_USER_EMAIL (or press Enter for default):"
echo "Default: $DEFAULT_TEST_EMAIL"
read -p "TEST_USER_EMAIL: " TEST_EMAIL
TEST_EMAIL=${TEST_EMAIL:-$DEFAULT_TEST_EMAIL}

# Prompt for TEST_USER_PASSWORD
echo ""
echo -e "${BLUE}🔐 Test User Password${NC}"
echo "Enter TEST_USER_PASSWORD (or press Enter for default):"
echo "Default: $DEFAULT_TEST_PASSWORD"
read -p "TEST_USER_PASSWORD: " TEST_PASSWORD
TEST_PASSWORD=${TEST_PASSWORD:-$DEFAULT_TEST_PASSWORD}

# Create .env.test.local
cat > .env.test.local << EOF
# Test Environment Variables
# Generated by setup-test-env.sh

# Test Database URL
DATABASE_URL_TEST=$DB_URL

# Test User Credentials
TEST_USER_EMAIL=$TEST_EMAIL
TEST_USER_PASSWORD=$TEST_PASSWORD

# Test Environment
NODE_ENV=test
EOF

echo ""
echo -e "${GREEN}✅ Test environment variables created in .env.test.local${NC}"
echo ""
echo "Variables set:"
echo "  DATABASE_URL_TEST=$DB_URL"
echo "  TEST_USER_EMAIL=$TEST_EMAIL"
echo "  TEST_USER_PASSWORD=$TEST_PASSWORD"
echo ""
echo "Next steps:"
echo "  1. Ensure your test database is running"
echo "  2. Run migrations: DATABASE_URL=$DB_URL npx prisma migrate deploy"
echo "  3. Run tests: npm test"
echo ""

